# Generated by Django 4.1.3 on 2022-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
