# Generated by Django 4.1.3 on 2022-11-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projboard', '0002_alter_article_content_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='projboard.subject'),
        ),
    ]
