# Generated by Django 4.1.3 on 2022-11-23 11:48

from django.db import migrations, transaction


class Migration(migrations.Migration):

    dependencies = [
        ('projboard', '0003_alter_article_subject_id'),
    ]

    def generate_subject_data(apps, schema_editor):
        from projboard.models.subject import Subject

        test_data = [
            'Sport',
            'Math',
            'Software',
            'Medicine and health',
            'Business',
            'Education',
            'Food',
            'Hobbies',
        ]
        with transaction.atomic():
            for s in test_data:
                Subject(name=s).save()

    operations = [
        migrations.RunPython(generate_subject_data),
    ]
