# Generated by Django 4.1.3 on 2023-01-19 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projboard', '0003_alter_article_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
