# Generated by chat-gpt

TURING = """A Turing Machine is a theoretical machine designed to perform calculations according to a set of rules.
It is often used as a theoretical model for the design and analysis of algorithms,
and is also known as a universal computer.

The concept of a Turing Machine was introduced by Alan Turing in his paper "On Computable Numbers,
with an Application to the Entscheidungsproblem" in 1936.
In this paper, Turing described a simple theoretical device that could read and write symbols on a tape,
and follow a set of rules to determine what to do next based on the symbol it was currently reading.

Turing Machines are theoretical constructs and do not physically exist,
but they have played a significant role in the development of the field of computer science.
They have influenced the design of real computers,
and many theoretical concepts and results in computer science can be described in terms of Turing Machines."""

RED_HAT = """Red Hat is a company that provides a range of software products and services,
including the Red Hat Enterprise Linux operating system and a range of related technologies.
The company is headquartered in Raleigh, North Carolina, and was founded in 1993.

Red Hat is known for its commitment to open source software and the development of open source technologies.
The company's products and services are built on top of a number of open source projects, including the Linux kernel,
the Gnome desktop environment, and the Apache web server.

Red Hat's products and services are used by a wide range of organizations,
including government agencies, Fortune 500 companies, and small and medium-sized businesses.
The company's offerings are designed to provide customers with stable, reliable,
and secure software solutions that can be easily integrated into their existing IT environments."""

TEL_HAI = """Tel-Hai college is a higher education institution located in the Northern District of Israel.
It was founded in 1979 and offers a range of academic programs in fields such as
engineering, computer science, business, education, and the arts.
The college also has a campus in Yeruham and a number of
partnership agreements with other institutions in Israel and abroad.
Tel-Hai college is accredited by the Council for Higher Education in Israel and is
recognized as a leading institution of higher education in the country."""
